// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: false,
  development: true,
  version: env.npm_package_version + '-dev',
  serverUrl: '/api',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],
  loadSampleData: true,
  //REST API server
  apiEndpoint: 'https://localhost:44378/api/v1',
  //Api_Endpoint: 'https://cat-netcore-api.azurewebsites.net/api/v1',
  //Api_Endpoint: 'https://mickleball-netcore-api.azurewebsites.net/api/v1',
  apiMockEndpoint: 'https://angular-datatables-demo-server.herokuapp.com',
  evaluationInstruction: {
    level20:
      '<div class="alert alert-success"><h4>Section 2 - Skill Evaluation</h4><span class="fw-normal">Select a rating for each skill code.</span><p><div>A = Solid, consistent performance <br>B = Good basic form, but needs work <br> C = Attempted but very poorly executed/needs work <br>D = Not observed or not able to execute </div></p></div>',
    level25:
      '<div class="alert alert-success"><h4>Section 2 - Skill Evaluation</h4><span class="fw-normal">Select a rating for each skill code.  Skill level 2.5 should ALSO possess all 2.0 skills.</span><p><div>A = Solid, consistent performance <br>B = Good basic form, but needs work <br> C = Attempted but very poorly executed/needs work <br>D = Not observed or not able to execute </div></p></div>',
    level30:
      '<div class="alert alert-success"><h4>Section 2 - Skill Evaluation</h4><span class="fw-normal">Select a rating for each skill code.  Skill level 3.0 should ALSO possess all 2.5 skills.</span><p><div>A = Solid, consistent performance <br>B = Good basic form, but needs work <br> C = Attempted but very poorly executed/needs work <br>D = Not observed or not able to execute </div></p></div>',
    level35:
      '<div class="alert alert-success"><h4>Section 2 - Skill Evaluation</h4><span class="fw-normal">Select a rating for each skill code.  Skill level 3.5 should ALSO possess all 3.0 skills.</span><p><div>A = Solid, consistent performance <br>B = Good basic form, but needs work <br> C = Attempted but very poorly executed/needs work <br>D = Not observed or not able to execute </div></p></div>',
    level40:
      '<div class="alert alert-success"><h4>Section 2 - Skill Evaluation</h4><span class="fw-normal">Select a rating for each skill code.  Skill level 4.0 should ALSO possess all 3.5 skills.</span><p><div>A = Solid, consistent performance <br>B = Good basic form, but needs work <br> C = Attempted but very poorly executed/needs work <br>D = Not observed or not able to execute </div></p></div>',
    level45:
      '<div class="alert alert-success"><h4>Section 2 - Skill Evaluation</h4><span class="fw-normal">Select a rating for each skill code.  Skill level 4.5 should ALSO possess all 4.0 skills.</span><p><div>A = Solid, consistent performance <br>B = Good basic form, but needs work <br> C = Attempted but very poorly executed/needs work <br>D = Not observed or not able to execute </div></p></div>',
    level50:
      '<div class="alert alert-success"><h4>Section 2 - Skill Evaluation</h4><span class="fw-normal">Select a rating for each skill code.  Skill level 5.0 should ALSO possess all 4.5 skills.</span><p><div>A = Solid, consistent performance <br>B = Good basic form, but needs work <br> C = Attempted but very poorly executed/needs work <br>D = Not observed or not able to execute </div></p></div>',
  },

  // skills list in googlesheet
  googleSheet: {
    apiKey: 'AIzaSyC3AgyGHXMyj8j-iFZ4ucrenprWrZm0VKI',
    spreadsheetId: '17zEoQvmjqBHoDykjxgun4upXg5QT6KooHnuAp_wXmac',
    worksheetGrades: 'Grades',
    worksheetSkills: 'Skills',
  },
  // training video search in youtube
  youtube: {
    apiUrl: 'https://www.googleapis.com/youtube/v3/search',
    apiKey: 'AIzaSyAq9W0tD3SJxtn6RE0aUcBseMMz_WcKhAU',
    maxResults: 10,
  },

  // Multi-Auth Configuration
  auth: {
    // Enable anonymous authentication for local development
    enableAnonymousAuth: true,
    // Default auth mode: 'oidc' | 'anonymous' | 'google' | 'facebook' | 'github' | 'microsoft'
    defaultAuthMode: 'anonymous',
    // Available auth providers
    availableProviders: ['anonymous', 'oidc', 'google', 'facebook', 'github', 'microsoft'],
    // Provider priority order for UI display
    providerPriority: ['anonymous', 'google', 'oidc', 'microsoft', 'facebook', 'github'],
  },

  // Anonymous Auth Configuration
  anonymousAuth: {
    enabled: true,
    sessionTimeout: 24 * 60 * 60 * 1000, // 24 hours in milliseconds
    defaultUser: {
      id: 'anonymous-user',
      name: 'Guest User',
      email: 'guest@pickleiq.local',
      roles: ['user'],
      permissions: ['rating.read', 'training.read', 'shop.read'],
    },
    warningMessage: 'You are using anonymous authentication for development purposes.',
    tokenPrefix: 'anonymous_',
  },

  // OAuth Provider Configurations
  oauthProviders: {
    // Custom OIDC Provider (existing IdentityServer)
    oidc: {
      enabled: true,
      name: 'Organization Login',
      description: 'Login with your organization account',
      icon: 'fas fa-shield-alt',
      brandColor: '#007bff',
      buttonClass: 'btn-primary',
      issuer: 'https://cat-token-identity.azurewebsites.net',
      clientId: 'MickleballClient',
      responseType: 'code',
      scope: 'openid profile email roles app.api.employeeprofile.read',
      redirectUri: window.location.origin + '/auth-callback',
      postLogoutRedirectUri: window.location.origin,
      silentRefreshRedirectUri: window.location.origin + '/silent-refresh.html',
      useSilentRefresh: true,
      silentRefreshTimeout: 50000,
      timeoutFactor: 0.25,
      sessionChecksEnabled: false,
      showDebugInformation: false,
      clearHashAfterLogin: false,
      nonceStateSeparator: 'semicolon',
    },

    // Google OAuth2
    google: {
      enabled: true, // Enable for development - requires client ID configuration in production
      name: 'Google',
      description: 'Continue with Google',
      icon: 'fab fa-google',
      brandColor: '#db4437',
      buttonClass: 'btn-danger',
      issuer: 'https://accounts.google.com',
      clientId: 'YOUR_GOOGLE_CLIENT_ID', // Replace with actual Google Client ID
      responseType: 'code',
      scope: 'openid profile email',
      redirectUri: window.location.origin + '/auth-callback',
      postLogoutRedirectUri: window.location.origin,
      silentRefreshRedirectUri: window.location.origin + '/silent-refresh.html',
      useSilentRefresh: true,
      strictDiscoveryDocumentValidation: false,
      showDebugInformation: false,
      clearHashAfterLogin: true,
      nonceStateSeparator: 'semicolon',
      // Google-specific OIDC discovery endpoint
      oidc: true,
      wellKnownEndpoints: 'https://accounts.google.com/.well-known/openid_configuration',
      // Google-specific parameters
      customUrlParams: {
        // Force account selection
        prompt: 'select_account',
        // Request additional Google-specific scopes if needed
        access_type: 'offline',
      },
      // Additional Google OAuth2 endpoints (fallback if OIDC discovery fails)
      loginUrl: 'https://accounts.google.com/oauth/authorize',
      tokenEndpoint: 'https://oauth2.googleapis.com/token',
      userinfoEndpoint: 'https://openidconnect.googleapis.com/v1/userinfo',
      jwksUri: 'https://www.googleapis.com/oauth2/v3/certs',
    },

    // Facebook OAuth2
    facebook: {
      enabled: true, // Enable for development - requires app ID configuration in production
      name: 'Facebook',
      description: 'Continue with Facebook',
      icon: 'fab fa-facebook-f',
      brandColor: '#4267B2',
      buttonClass: 'btn-primary',
      issuer: 'https://www.facebook.com',
      clientId: 'YOUR_FACEBOOK_APP_ID', // Replace with actual Facebook App ID
      responseType: 'code',
      scope: 'email public_profile', // Facebook uses different scope format
      redirectUri: window.location.origin + '/auth-callback',
      postLogoutRedirectUri: window.location.origin,
      useSilentRefresh: false, // Facebook doesn't support OIDC silent refresh
      strictDiscoveryDocumentValidation: false,
      showDebugInformation: false,
      clearHashAfterLogin: true,
      // Facebook OAuth2 specific configuration
      oidc: false, // Facebook doesn't fully support OIDC, use OAuth2
      loginUrl: 'https://www.facebook.com/v18.0/dialog/oauth',
      tokenEndpoint: 'https://graph.facebook.com/v18.0/oauth/access_token',
      userinfoEndpoint: 'https://graph.facebook.com/v18.0/me',
      // Facebook-specific parameters
      customUrlParams: {
        display: 'popup',
        // Request specific Facebook fields
        fields: 'id,name,email,picture.type(large)',
        // Facebook API version
        auth_type: 'rerequest',
      },
      // Additional Facebook configuration
      requireHttps: true,
      sessionChecksEnabled: false,
      // Custom token validation for Facebook
      skipIssuerCheck: true, // Facebook tokens don't include standard issuer
      disablePKCE: false, // Facebook supports PKCE
    },

    // GitHub OAuth2
    github: {
      enabled: true, // Enable for development - requires client ID configuration in production
      name: 'GitHub',
      description: 'Continue with GitHub',
      icon: 'fab fa-github',
      brandColor: '#333',
      buttonClass: 'btn-dark',
      issuer: 'https://github.com',
      clientId: 'YOUR_GITHUB_CLIENT_ID', // Replace with actual GitHub Client ID
      responseType: 'code',
      scope: 'read:user user:email', // GitHub-specific scopes
      redirectUri: window.location.origin + '/auth-callback',
      postLogoutRedirectUri: window.location.origin,
      useSilentRefresh: false, // GitHub doesn't support OIDC silent refresh
      strictDiscoveryDocumentValidation: false,
      showDebugInformation: false,
      clearHashAfterLogin: true,
      // GitHub OAuth2 specific configuration
      oidc: false, // GitHub uses OAuth2, not OIDC
      loginUrl: 'https://github.com/login/oauth/authorize',
      tokenEndpoint: 'https://github.com/login/oauth/access_token',
      userinfoEndpoint: 'https://api.github.com/user',
      // GitHub-specific parameters
      customUrlParams: {
        // Allow user to choose which account to use
        prompt: 'select_account',
        // Request specific permissions
        allow_signup: 'true',
      },
      // Additional GitHub configuration
      requireHttps: true,
      sessionChecksEnabled: false,
      // Custom token validation for GitHub
      skipIssuerCheck: true, // GitHub tokens don't include standard issuer
      disablePKCE: false, // GitHub supports PKCE
      // GitHub API configuration
      apiHeaders: {
        Accept: 'application/vnd.github.v3+json',
        'User-Agent': 'PickleIQ-App',
      },
      // Additional endpoints for GitHub user data
      emailEndpoint: 'https://api.github.com/user/emails',
    },

    // Microsoft/Azure AD OAuth2
    microsoft: {
      enabled: true, // Enable for development - requires client ID configuration in production
      name: 'Microsoft',
      description: 'Continue with Microsoft',
      icon: 'fab fa-microsoft',
      brandColor: '#00a1f1',
      buttonClass: 'btn-info',
      issuer: 'https://login.microsoftonline.com/common/v2.0',
      clientId: 'YOUR_MICROSOFT_CLIENT_ID', // Replace with actual Microsoft/Azure AD Client ID
      responseType: 'code',
      scope: 'openid profile email User.Read', // Microsoft-specific scopes
      redirectUri: window.location.origin + '/auth-callback',
      postLogoutRedirectUri: window.location.origin,
      silentRefreshRedirectUri: window.location.origin + '/silent-refresh.html',
      useSilentRefresh: true,
      strictDiscoveryDocumentValidation: false,
      showDebugInformation: false,
      clearHashAfterLogin: true,
      nonceStateSeparator: 'semicolon',
      // Microsoft OIDC configuration
      oidc: true,
      wellKnownEndpoints: 'https://login.microsoftonline.com/common/v2.0/.well-known/openid_configuration',
      // Microsoft-specific parameters
      customUrlParams: {
        // Force account selection
        prompt: 'select_account',
        // Specify tenant (common, organizations, consumers)
        // 'common' allows both work/school and personal accounts
        domain_hint: '', // Leave empty for account selection
      },
      // Additional Microsoft configuration
      requireHttps: true,
      sessionChecksEnabled: true,
      timeoutFactor: 0.25,
      silentRefreshTimeout: 50000,
      // Microsoft Graph API endpoints
      loginUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
      tokenEndpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
      userinfoEndpoint: 'https://graph.microsoft.com/v1.0/me',
      jwksUri: 'https://login.microsoftonline.com/common/discovery/v2.0/keys',
      // Logout endpoint for proper session cleanup
      logoutUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/logout',
    },
  },
  sampleModel40: {
    level: '4.0',
    playername: 'Fuji Nguyen',
    playeremail: 'fuji.nguyen@workcontrol.com',
    assessmentDate: '2022-10-24',
    '40-1': 'D',
    '40-2': 'A',
    '40-3': 'A',
    '40-4': 'A',
    '40-5': 'A',
    '40-6': 'A',
    '40-7': 'A',
    '40-8': 'A',
    '40-9': 'A',
    '40-10': 'A',
    '40-11': 'A',
    '40-12': 'D',
    '40-13': 'A',
    '40-14': 'B',
    '40-15': 'A',
    '40-16': 'A',
    '40-17': 'A',
    '40-18': 'A',
    '40-19': 'B',
    '40-20': 'A',
    '40-21': 'A',
    '40-22': 'C',
    evaluatorname: 'Emily Nguyen',
    evaluatoremail: 'emily@gmail.com',
    Notes: 'Lefty user',
    terms: true,
  },
};
