// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: false,
  development: true,
  version: env.npm_package_version + '-dev',
  serverUrl: '/api',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],
  loadSampleData: true,
  //REST API server
  apiEndpoint: 'https://localhost:44378/api/v1',
  //Api_Endpoint: 'https://cat-netcore-api.azurewebsites.net/api/v1',
  //Api_Endpoint: 'https://mickleball-netcore-api.azurewebsites.net/api/v1',
  apiMockEndpoint: 'https://angular-datatables-demo-server.herokuapp.com',
  evaluationInstruction: {
    level20:
      '<div class="alert alert-success"><h4>Section 2 - Skill Evaluation</h4><span class="fw-normal">Select a rating for each skill code.</span><p><div>A = Solid, consistent performance <br>B = Good basic form, but needs work <br> C = Attempted but very poorly executed/needs work <br>D = Not observed or not able to execute </div></p></div>',
    level25:
      '<div class="alert alert-success"><h4>Section 2 - Skill Evaluation</h4><span class="fw-normal">Select a rating for each skill code.  Skill level 2.5 should ALSO possess all 2.0 skills.</span><p><div>A = Solid, consistent performance <br>B = Good basic form, but needs work <br> C = Attempted but very poorly executed/needs work <br>D = Not observed or not able to execute </div></p></div>',
    level30:
      '<div class="alert alert-success"><h4>Section 2 - Skill Evaluation</h4><span class="fw-normal">Select a rating for each skill code.  Skill level 3.0 should ALSO possess all 2.5 skills.</span><p><div>A = Solid, consistent performance <br>B = Good basic form, but needs work <br> C = Attempted but very poorly executed/needs work <br>D = Not observed or not able to execute </div></p></div>',
    level35:
      '<div class="alert alert-success"><h4>Section 2 - Skill Evaluation</h4><span class="fw-normal">Select a rating for each skill code.  Skill level 3.5 should ALSO possess all 3.0 skills.</span><p><div>A = Solid, consistent performance <br>B = Good basic form, but needs work <br> C = Attempted but very poorly executed/needs work <br>D = Not observed or not able to execute </div></p></div>',
    level40:
      '<div class="alert alert-success"><h4>Section 2 - Skill Evaluation</h4><span class="fw-normal">Select a rating for each skill code.  Skill level 4.0 should ALSO possess all 3.5 skills.</span><p><div>A = Solid, consistent performance <br>B = Good basic form, but needs work <br> C = Attempted but very poorly executed/needs work <br>D = Not observed or not able to execute </div></p></div>',
    level45:
      '<div class="alert alert-success"><h4>Section 2 - Skill Evaluation</h4><span class="fw-normal">Select a rating for each skill code.  Skill level 4.5 should ALSO possess all 4.0 skills.</span><p><div>A = Solid, consistent performance <br>B = Good basic form, but needs work <br> C = Attempted but very poorly executed/needs work <br>D = Not observed or not able to execute </div></p></div>',
    level50:
      '<div class="alert alert-success"><h4>Section 2 - Skill Evaluation</h4><span class="fw-normal">Select a rating for each skill code.  Skill level 5.0 should ALSO possess all 4.5 skills.</span><p><div>A = Solid, consistent performance <br>B = Good basic form, but needs work <br> C = Attempted but very poorly executed/needs work <br>D = Not observed or not able to execute </div></p></div>',
  },

  // skills list in googlesheet
  googleSheet: {
    apiKey: 'AIzaSyC3AgyGHXMyj8j-iFZ4ucrenprWrZm0VKI',
    spreadsheetId: '17zEoQvmjqBHoDykjxgun4upXg5QT6KooHnuAp_wXmac',
    worksheetGrades: 'Grades',
    worksheetSkills: 'Skills',
  },
  // training video search in youtube
  youtube: {
    apiUrl: 'https://www.googleapis.com/youtube/v3/search',
    apiKey: 'AIzaSyAq9W0tD3SJxtn6RE0aUcBseMMz_WcKhAU',
    maxResults: 10,
  },

  // Multi-Auth Configuration
  auth: {
    // Enable anonymous authentication for local development
    enableAnonymousAuth: true,
    // Default auth mode: 'oidc' | 'anonymous' | 'google' | 'facebook' | 'github' | 'microsoft'
    defaultAuthMode: 'anonymous',
    // Available auth providers
    availableProviders: ['anonymous', 'oidc', 'google', 'facebook', 'github', 'microsoft'],
    // Provider priority order for UI display
    providerPriority: ['anonymous', 'google', 'oidc', 'microsoft', 'facebook', 'github'],
  },

  // Anonymous Auth Configuration
  anonymousAuth: {
    enabled: true,
    sessionTimeout: 24 * 60 * 60 * 1000, // 24 hours in milliseconds
    defaultUser: {
      id: 'anonymous-user',
      name: 'Guest User',
      email: 'guest@pickleiq.local',
      roles: ['user'],
      permissions: ['rating.read', 'training.read', 'shop.read'],
    },
    warningMessage: 'You are using anonymous authentication for development purposes.',
    tokenPrefix: 'anonymous_',
  },

  // OAuth Provider Configurations
  oauthProviders: {
    // Custom OIDC Provider (existing IdentityServer)
    oidc: {
      enabled: true,
      name: 'Organization Login',
      description: 'Login with your organization account',
      icon: 'fas fa-shield-alt',
      brandColor: '#007bff',
      buttonClass: 'btn-primary',
      issuer: 'https://cat-token-identity.azurewebsites.net',
      clientId: 'MickleballClient',
      responseType: 'code',
      scope: 'openid profile email roles app.api.employeeprofile.read',
      redirectUri: window.location.origin + '/auth-callback',
      postLogoutRedirectUri: window.location.origin,
      silentRefreshRedirectUri: window.location.origin + '/silent-refresh.html',
      useSilentRefresh: true,
      silentRefreshTimeout: 50000,
      timeoutFactor: 0.25,
      sessionChecksEnabled: false,
      showDebugInformation: false,
      clearHashAfterLogin: false,
      nonceStateSeparator: 'semicolon',
    },

    // Google OAuth2
    google: {
      enabled: false, // Disabled by default - requires client ID configuration
      name: 'Google',
      description: 'Continue with Google',
      icon: 'fab fa-google',
      brandColor: '#db4437',
      buttonClass: 'btn-danger',
      issuer: 'https://accounts.google.com',
      clientId: '', // Configure with your Google Client ID
      responseType: 'code',
      scope: 'openid profile email',
      redirectUri: window.location.origin + '/auth-callback',
      postLogoutRedirectUri: window.location.origin,
      silentRefreshRedirectUri: window.location.origin + '/silent-refresh.html',
      useSilentRefresh: true,
      strictDiscoveryDocumentValidation: false,
    },

    // Facebook OAuth2
    facebook: {
      enabled: false, // Disabled by default - requires app ID configuration
      name: 'Facebook',
      description: 'Continue with Facebook',
      icon: 'fab fa-facebook-f',
      brandColor: '#4267B2',
      buttonClass: 'btn-primary',
      issuer: 'https://www.facebook.com',
      clientId: '', // Configure with your Facebook App ID
      responseType: 'code',
      scope: 'openid profile email',
      redirectUri: window.location.origin + '/auth-callback',
      postLogoutRedirectUri: window.location.origin,
      useSilentRefresh: false, // Facebook doesn't support silent refresh
      strictDiscoveryDocumentValidation: false,
      customUrlParams: {
        display: 'popup',
      },
    },

    // GitHub OAuth2
    github: {
      enabled: false, // Disabled by default - requires client ID configuration
      name: 'GitHub',
      description: 'Continue with GitHub',
      icon: 'fab fa-github',
      brandColor: '#333',
      buttonClass: 'btn-dark',
      issuer: 'https://github.com',
      clientId: '', // Configure with your GitHub Client ID
      responseType: 'code',
      scope: 'openid profile email',
      redirectUri: window.location.origin + '/auth-callback',
      postLogoutRedirectUri: window.location.origin,
      useSilentRefresh: false, // GitHub doesn't support OIDC silent refresh
      strictDiscoveryDocumentValidation: false,
      loginUrl: 'https://github.com/login/oauth/authorize',
      tokenEndpoint: 'https://github.com/login/oauth/access_token',
      userinfoEndpoint: 'https://api.github.com/user',
    },

    // Microsoft/Azure AD OAuth2
    microsoft: {
      enabled: false, // Disabled by default - requires client ID configuration
      name: 'Microsoft',
      description: 'Continue with Microsoft',
      icon: 'fab fa-microsoft',
      brandColor: '#00a1f1',
      buttonClass: 'btn-info',
      issuer: 'https://login.microsoftonline.com/common/v2.0',
      clientId: '', // Configure with your Microsoft/Azure AD Client ID
      responseType: 'code',
      scope: 'openid profile email',
      redirectUri: window.location.origin + '/auth-callback',
      postLogoutRedirectUri: window.location.origin,
      silentRefreshRedirectUri: window.location.origin + '/silent-refresh.html',
      useSilentRefresh: true,
      strictDiscoveryDocumentValidation: false,
    },
  },
  sampleModel40: {
    level: '4.0',
    playername: 'Fuji Nguyen',
    playeremail: 'fuji.nguyen@workcontrol.com',
    assessmentDate: '2022-10-24',
    '40-1': 'D',
    '40-2': 'A',
    '40-3': 'A',
    '40-4': 'A',
    '40-5': 'A',
    '40-6': 'A',
    '40-7': 'A',
    '40-8': 'A',
    '40-9': 'A',
    '40-10': 'A',
    '40-11': 'A',
    '40-12': 'D',
    '40-13': 'A',
    '40-14': 'B',
    '40-15': 'A',
    '40-16': 'A',
    '40-17': 'A',
    '40-18': 'A',
    '40-19': 'B',
    '40-20': 'A',
    '40-21': 'A',
    '40-22': 'C',
    evaluatorname: 'Emily Nguyen',
    evaluatoremail: 'emily@gmail.com',
    Notes: 'Lefty user',
    terms: true,
  },
};
